In [9]:
import scipy.stats as sts
import scipy.misc as sm
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from IPython.display import display
%matplotlib inline

In [27]:
data = pd.read_csv('marks.csv', header=None)
n = data.shape[0]
nrange = np.arange(n)
m = data.shape[1]

print (n, m)

data = data.fillna(0)
data.head()

87 14


0    1    2    3    4    5    6    7    8    9    10   11  \
0     Garkavyj Andrej  3.0  3.0  3.0  3.0  1.0  2.0  3.0  3.0  3.0  3.0 -1.0   
1  Gol'cova Ekaterina  3.0  3.0  3.0  3.0  0.0  3.0  3.0  3.0  3.0  3.0 -1.0   
2     Grishkin Maksim  1.0  3.0  3.0  1.0  0.0  0.0  0.0  0.0  0.0  3.0 -1.0   
3     Dmitriev Daniil  3.0  2.0  2.0  1.0  0.0  3.0  3.0  1.0  3.0  3.0 -1.0   
4       Egorova Alena  3.0  3.0  3.0  3.0  0.0  2.0  2.0  1.0  1.0  3.0 -1.0   

    12   13  
0  3.0  3.0  
1  3.0  3.0  
2  0.0  0.0  
3  3.0  3.0  
4  3.0  3.0

In [32]:
names = ["Karjamin Andrej", "Nurgalieva Jegdelija", "Mudrova Irina", "Pechatnov Jurij"]
xs = []
for name in names:
    x = data[data[0] == "Karjamin Andrej"]
    xs.append(np.array(x)[0][1:])

probnum = len(xs[0])
print(np.array(xs).T)

[[2.0 2.0 2.0 2.0]
 [3.0 3.0 3.0 3.0]
 [3.0 3.0 3.0 3.0]
 [1.0 1.0 1.0 1.0]
 [0.0 0.0 0.0 0.0]
 [2.0 2.0 2.0 2.0]
 [0.0 0.0 0.0 0.0]
 [0.0 0.0 0.0 0.0]
 [0.0 0.0 0.0 0.0]
 [3.0 3.0 3.0 3.0]
 [1.0 1.0 1.0 1.0]
 [3.0 3.0 3.0 3.0]
 [-1.0 -1.0 -1.0 -1.0]]


In [33]:
maxmark = 10
markrange = np.arange(maxmark + 1)
def est(x):
    pe = []
    for pi in range(1, m):
        if x[pi - 1] != -1:
            pe.append(0)
            continue
        prior_alphas = []
        for mark in markrange:
            pcnt = 1.0 * np.sum(data[pi] == mark) / np.sum(data[pi] != 0)
            prior_alphas.append(pcnt)
        #print alphas
        poster_alphas = []
        for mark, prior_alpha in zip(markrange, prior_alphas):
            talpha = prior_alpha + np.sum(x == mark)
            #print np.sum(x == mark)
            poster_alphas.append(talpha)
        poster_alphas = np.array(poster_alphas)
        probas = poster_alphas / np.sum(poster_alphas)
        e = 0
        for mark in markrange:
            e += mark * probas[mark]
        pe.append(e)
    return pe

In [15]:
print(est(xs[0]))

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1.5042643923240937]


In [17]:
for name, x in zip(names, xs):
    print(name)
    print(x)
    print(np.round(est(x), 1))

Karjamin Andrej
[2.0 3.0 3.0 1.0 0.0 2.0 0.0 0.0 0.0 3.0 1.0 3.0 -1.0]
[ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   1.5]
Nurgalieva Jegdelija
[2.0 3.0 3.0 1.0 0.0 2.0 0.0 0.0 0.0 3.0 1.0 3.0 -1.0]
[ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   1.5]
Mudrova Irina
[2.0 3.0 3.0 1.0 0.0 2.0 0.0 0.0 0.0 3.0 1.0 3.0 -1.0]
[ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   1.5]
Pechatnov Jurij
[2.0 3.0 3.0 1.0 0.0 2.0 0.0 0.0 0.0 3.0 1.0 3.0 -1.0]
[ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   1.5]


In [34]:
matr = np.array(data)
names = matr[0]
matr = matr[:, 1:]
print(matr)
for row in matr:
    row += est(row)
print(matr)

marks = []
for row in matr:
    mark = np.round(np.mean(row) / 3 * 10)
    marks.append(mark)

marks = np.array(marks)

print(marks)
len(marks)

[[3.0 3.0 3.0 ..., -1.0 3.0 3.0]
 [3.0 3.0 3.0 ..., -1.0 3.0 3.0]
 [1.0 3.0 3.0 ..., -1.0 0.0 0.0]
 ..., 
 [3.0 3.0 3.0 ..., -1.0 0.0 0.0]
 [3.0 3.0 3.0 ..., -1.0 3.0 0.0]
 [2.0 3.0 3.0 ..., -1.0 3.0 2.0]]
[[3.0 3.0 3.0 ..., 1.6702002355712602 3.0 3.0]
 [3.0 3.0 3.0 ..., 1.6702002355712602 3.0 3.0]
 [1.0 3.0 3.0 ..., -0.0918727915194345 0.0 0.0]
 ..., 
 [3.0 3.0 3.0 ..., 0.22850412249705543 0.0 0.0]
 [3.0 3.0 3.0 ..., 1.1095406360424027 3.0 0.0]
 [2.0 3.0 3.0 ..., 1.0294464075382805 3.0 2.0]]
[ 9.  9.  3.  7.  7.  4.  7.  8.  5.  7.  6.  9.  7.  5.  6.  6. -0.  8.
  8.  7.  1.  6.  7.  7.  7.  5.  7.  8.  5.  7.  5. -0.  8.  8.  1.  1.
  6. -2.  6.  2.  5.  6.  2.  1.  5.  6.  4.  3.  6.  3. -1.  5.  5.  5.
  6.  6.  6. -0.  1.  8.  5.  1.  6.  2.  5.  2.  6.  3.  8. -0.  6.  4.
  5.  6.  5.  5. -0.  9.  9.  7.  5.  9.  6.  7.  4.  7.  7.]


87

In [8]:
est2 = np.sum(marks < 3.0)
print(est2)

17


In [9]:
est3 = np.sum(np.logical_and(marks >= 3.0, marks < 5.0))
print(est3)

8


In [10]:
est4 = np.sum(np.logical_and(marks >= 5.0, marks < 8.0))
print(est4)

48


In [22]:
est5 = np.sum(marks >= 8.0)
print(est5)

14


In [25]:
for mark in range(2, 10):
    ids = marks == mark
    mean = np.mean(matr[ids])
    print(mark, mean)

2 0.5684158152670258
3 0.8664014836022991
4 1.1783026391451195
5 1.5081982736224748
6 1.8499565020188504
7 2.097308774472427
8 2.408928448272365
9 2.6669384796593274


In [26]:
print ("!= 2", np.mean(matr[marks >= 3]))

!= 2 1.8641705640641562
